### ISSUE TITLE
Executor returns "Invalid or missing options" 

### ISSUE THREAD

**Issue by 580farm** [etsy/nagios-herald#39]
Is this likely because there's a nagios env variable not getting loaded? The code doesn't make it clear what env options are required beyond reply-to and message-type. I tried with a environment file as well, and adding -d and --trace didn't change the generic error that's returned to standard output:

[2016-01-21 15:32:20 -0800] FATAL -- nagios-herald (NagiosHerald::Executor): Invalid or missing options

I'm invoking it thusly, with a test file to test notifications:

 /usr/local/nagios-herald/bin/nagios-herald -r ops@example.com -e /usr/local/nagios-herald/test/env_files/nagios_vars -y nagios@example.com

are there/is there a list of what environment variables are required? Are there any test configs I can work backwards from?

**Comment by RyanFrantz** [comment]
Looks like you're missing the ``-m, --message-type`` argument. The ``--help`` argument should describe which arguments are required (look for ``[REQUIRED]``).

I wrote the help output that way because the ``Choice`` gem doesn't expose which arguments are explicitly required.
