### ISSUE TITLE
Where can one view the code for /usr/local/nagios-herald/bin/nagios-herald

### ISSUE THREAD

**Issue by og-bash-scripts** [etsy/nagios-herald#51]
Hello community,

I am trying to review the nagios.cmd file on how the output of the npre commands are formated.

you mention the following on [https://github.com/etsy/nagios-herald/blob/master/docs/nagios-config.md](https://github.com/etsy/nagios-herald/blob/master/docs/nagios-config.md )

> NOTE: $_HOSTMESSAGE_FORMATTER_NAME$ and $_SERVICEMESSAGE_FORMATTER_NAME$ are Nagios macros, generated from a custom variable in a relevant service check definition.

It looks like the file is located here: 
`/usr/local/nagios-herald/bin/nagios-herald`

I am trying to review how the nagios-hearld parses the output of a command that is ran on the targeted monitored server with the npre and how that output is formatted and fed into the email body.

thanks in advance.

**Comment by RyanFrantz** [comment]
This is done by adding a custom variable in a Nagios defintion like the example in https://github.com/etsy/nagios-herald/blob/master/docs/nagios-config.md#service-configuration

For example `$_SERVICEMESSAGE_FORMATTER_NAME$` is generated by Nagios as a result of having a custom variable called `_message_formatter_name` in a Nagios service definition.
